name = "cloudmanager-frontend"
compatibility_date = "2024-01-15"

# Pages build configuration
pages_build_output_dir = "dist"

# Environment variables for Pages
[env.production.vars]
VITE_API_URL = "https://cloudmanager.lamado.workers.dev"

[env.preview.vars]
VITE_API_URL = "https://cloudmanager.lamado.workers.dev"