# Backend Worker Configuration
name = "cloudmanager"
main = "src/worker/index.ts"
compatibility_date = "2024-01-15"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "cloudmanager-db"
database_id = "d5a88802-2ef8-4878-b882-97f8b2aa37af"

# Production environment for the API worker
[env.production]
name = "cloudmanager"

[env.production.vars]
ENVIRONMENT = "production"

# Development environment
[env.development]
name = "cloudmanager"

[env.development.vars]
ENVIRONMENT = "development"