name = "cloudmanager"
main = "src/worker/index.ts"
compatibility_date = "2024-01-15"
route = ""
workers_dev = true

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secret-jwt-key-change-in-production-2024"

[[d1_databases]]
binding = "DB"
database_name = "cloudmanager-db"
database_id = "d5a88802-2ef8-4878-b882-97f8b2aa37af"

# Production environment
[env.production]
name = "cloudmanager"

[env.production.vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secret-jwt-key-change-in-production-2024"

# Development environment
[env.development]
name = "cloudmanager-dev"

[env.development.vars]
ENVIRONMENT = "development"
JWT_SECRET = "dev-jwt-secret-key"