# Frontend Pages Configuration
name = "cloudmanager-frontend"
compatibility_date = "2024-01-15"

# Pages build configuration
pages_build_output_dir = "dist"

[build]
command = "npm run build"

# Environment variables for Pages
[env.production.vars]
VITE_API_URL = "https://cloudmanager-api.lamado.workers.dev"

[env.preview.vars]
VITE_API_URL = "https://cloudmanager-api-dev.lamado.workers.dev"

# Backend Worker Configuration (separate deployment)
# Deploy with: wrangler deploy --config wrangler.worker.toml